### ISSUE TITLE
After moved higher speed profiles ,i don't see them in User presets - Orca 1.9.0

### ISSUE THREAD

**Issue by Yokosa** [w34sel/3D-Printing#2]
Hi,
Thanks for your hard work, however, I have a small problem. I have moved the higher speed profiles as described (Orca user profiles copy default to "C:\Users<USERNAME>\AppData\Roaming\OrcaSlicer\user" (Higher speed)) but I don't see them in User presets. Are they adapted to Orca 1.9.0 ? I don't see them in the main branch after your changes today.

**Comment by w34sel** [comment]
Hey, 
sry, they are not adapted yet, working on it :)

**Comment by w34sel** [comment]
updated check it out

**Comment by Yokosa** [comment]
Thanks, now everything works!
